ps_blog_project/ps_blog_app/urls.py
from django.urls import path
from ps_blog_app import views
from django.contrib import admin

app_name = 'ps_blog_app'
urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('upcoming_titles/', views.upcoming_titles, name='upcoming'),
    path('register/', views.register, name='register'),
    path('login_page/', views.login_page, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create_blog/', views.create_blog, name='create'),
    path('categories/<category>/', views.blog_category, name='blog_category'),
]

ps_blog_project/ps_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from ps_blog_app import views

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('ps_blog_app/', include('ps_blog_app.urls')),
    path('categories/<category>/', views.blog_category, name='blog_category'),
    path('register/', views.register, name='register'),
    path('login_page', views.login_page, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create_blog/', views.create_blog, name='create'),
    path('admin/', admin.site.urls),
]

ps_blog_project/ps_blog_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Model will inherit from Django 'User' model.
class UserProfileInfo(models.Model): 
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    posts = models.ManyToManyField('blog_post', related_name='b_posts')

    def __str__(self):
        return self.user.username

# All blog posts must have a category.
class category(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

# Blog posts that can be created if a user is logged in.
class blog_post(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('category', related_name='posts')

    def __str__(self):
        return self.title
# Model for comments on a blog post.
class comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog_post', on_delete=models.CASCADE)

ps_blog_project/ps_blog_app/forms.py
from django import forms
from ps_blog_app.models import UserProfileInfo, blog_post
from django.contrib.auth.models import User


# To allow registered users to create a post.
class create_blog_form(forms.Form):
    title = forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder" : "Your post name"
    })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
        "class": "form-control",
        "placeholder": "Create your post!"
    })
    )



# Form for commenting on a blog post.
class comment_form(forms.Form):
    author = forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class": "form-control",
        "placeholder" : "Your name"
    })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
        "class": "form-control",
        "placeholder": "Leave a comment!"
    })
    )

# Login form for login.html.
class login_form(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')
   
   
   
    """
    user_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "username",
    }), label='username')

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class" : "form-control",

    }), label='password')
    """


# User profile form for registration page.
class UserProfileInfoForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput(attrs={
    #    "class" : "form-control",
    #}), label='password')

    class Meta():
        model = User
        help_texts = {
            'username' : None,
        }


        fields = ('username', 'email', 'password')
        widgets = {
            'username' : forms.TextInput(attrs={
                'class' : u'form-control',
            }),

            'email' : forms.TextInput(attrs={
                'class' : u'form-control',
            }),

            'password' : forms.PasswordInput(attrs={
                'class' : u'form-control',
            })

        }


        labels = {
            'username' : 'username',
            'email' : 'email',
            'password' : 'password',
        }

ps_blog_project/ps_blog_app/views.py
from django.shortcuts import render, redirect
from ps_blog_app.models import category, blog_post, comment, UserProfileInfo
from ps_blog_app.forms import comment_form, UserProfileInfoForm, login_form, create_blog_form
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required



def blog_index(request):

    posts = blog_post.objects.all().order_by('-created_on')
    for u in User.objects.all(): 
        print(u.username)

    context = {
        "posts": posts,
    }
    return render(request, 'ps_blog_app/blog_index.html', context)

# Login page view.
def login_page(request):
    logged_in = False

    logged_in_form = login_form()
    # If user tried to POST, authenticate their credentials.
    if request.method == 'POST':
        logged_in_form = login_form(data=request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        # If user is registered in database.
        if user:
            if user.is_active:
                login(request, user) # login the user.
                logged_in = True

                posts = blog_post.objects.all().order_by('-created_on')
                return HttpResponseRedirect(reverse('blog_index'))

        # Need to change this to show an error message on login page.
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username, password))

    elif logged_in == False and request.method != 'POST':
        return render(request, 'ps_blog_app/login.html', {'login_form':logged_in_form, 'logged_in':logged_in})

    else:
        return render(request, 'ps_blog_app/login.html', {'login_form':logged_in_form, 'logged_in':logged_in})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog_index'))

# Used to add new users to be able to post blogs.
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()


            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserProfileInfoForm()

    return render(request, 'ps_blog_app/register.html', {'user_form': user_form,  'registered': registered})


def upcoming_titles(request):
    return render(request, 'ps_blog_app/upcoming.html')

def blog_category(request, category):
    # Use filter query to order the posts by the dates they were created on.
    # The '-' infront of 'created_on' specifies to start with the largest value.
    posts = blog_post.objects.filter( categories__name__contains=category ).order_by( '-created_on' )

    context = {
        "category": category,
        "posts" : posts
    }

    return render(request, 'ps_blog_app/blog_category.html', context)

def blog_detail(request, pk):
    # Will be used as template var in blog_detail.html.
    b_post = blog_post.objects.get(pk=pk)

    form = comment_form()
    # Check for post request in the server.
    if request.method == 'POST':
        # Create new comment if so.
        form = comment_form(request.POST)
        # Make sure all fields from comment() have been entered in correctly.
        if form.is_valid():
            new_comment = comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=b_post
            )
            new_comment.save()

    # Query database for all the comments assigned by the given post.
    comments = comment.objects.filter(post=b_post)

    context = {
        "post": b_post,
        "comments": comments,
        "form": form,
    }
    return render(request, 'ps_blog_app/blog_detail.html', context)

@login_required
def create_blog(request):
    categories = category.objects.all()
    blog_post_form = create_blog_form()
    if request.method == 'POST':
        blog_post_form = create_blog_form(request.POST)

        if blog_post_form.is_valid():
            new_post = blog_post(
                title=blog_post_form.cleaned_data["title"],
                body=blog_post_form.cleaned_data["body"],
            )
            #new_post.author = user.username
            new_post.save()
            return HttpResponseRedirect(reverse('blog_index'))

    context = {
        "categories" : categories,
        "blog_form" : blog_post_form,
    }
    return render(request, 'ps_blog_app/create_blog.html', context)

ps_blog_project/templates/ps_blog_app/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <!-- predefined jumbotron-->
    <style type="text/css">
        .jumbotron {
          padding: 4rem 2rem;
          margin-bottom: 2rem;
          background-color: var(--bs-light);
          border-radius: .3rem;  
        }
    </style>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- Bootstrap cdn link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/ps_blog_master.css' %}"/>

    <!-- Google font link -->
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@700&display=swap" rel="stylesheet">

</head>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3be229;">
  <a id="mg_brand" class="navbar-brand" href="#">MGblogs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a id="home_link" class="nav-link" href="{% url 'ps_blog_app:blog_index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a id="upcoming_link" class="nav-link" href="{% url 'ps_blog_app:upcoming' %}">Upcoming Titles</a>
      </li>
      <!-- links to be displayed if the user is currently logged in-->
      {% if user.is_authenticated %}
      <a class="nav-link" id='user_name' href="{% url 'ps_blog_app:blog_index' %}">{{ user.username }}</a>
      <a class="nav-link" id="create_link" href="{% url 'ps_blog_app:create' %}">create post</a>
      <a class="nav-link" id='log_out' href="{% url 'ps_blog_app:logout' %}">logout</a>
      <!-- otherwise, don't display a name and show the login and register links. -->
      {% else %}
      <a class="nav-link" id='login_link' href="{% url 'ps_blog_app:login' %}">login</a>
      <a class="nav-link" id='register_link' href="{% url 'ps_blog_app:register' %}">register</a>
      {% endif %} 
    </ul>
  </div>
</nav>
<!--
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3be229;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#blog-info-div" aria-controls="blog-info-div" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="blog-info-div">
        <div class="navbar-nav">
          <a class="nav-link" id='home_link' href="{% url 'ps_blog_app:blog_index' %}">Home</a>
          <a class="nav-link" id='upcoming_link' href="{% url 'ps_blog_app:upcoming' %}">upcoming titles</a>
           links to be displayed if the user is currently logged in
          {% if user.is_authenticated %}
          <a class="nav-link" id='user_name' href="{% url 'ps_blog_app:blog_index' %}">{{ user.username }}</a>
          <a class="nav-link" id="create_link" href="{% url 'ps_blog_app:create' %}">create post</a>
          <a class="nav-link" id='log_out' href="{% url 'ps_blog_app:logout' %}">logout</a>
           otherwise, don't display a name and show the login and register links. 
          {% else %}
          <a class="nav-link" id='login_link' href="{% url 'ps_blog_app:login' %}">login</a>
          <a class="nav-link" id='register_link' href="{% url 'ps_blog_app:register' %}">register</a>
          {% endif %}      
        </div>
      </div>
    </div>
  </nav> -->

{%block body_block%}
  <body>
      
  </body>
  {% endblock %}
  <!-- Jquery for nav icon -->
  </html>

ps_blog_project/templates/ps_blog_app/blog_category.html
{% extends 'ps_blog_app/base.html'%}
{% block body_block %}
<div class='col-md-8 offset-md-2'>
    <h1 id='category_header'>{{ category | title }}</h1>
    
    <hr>
    {% for post in posts %}
    <!-- link to the blog_detail view and show the post title -->
    <h2><a href="{% url 'ps_blog_app:blog_detail' post.pk %}">{{ post.title }}</a></h2>
    <small>
        <!-- show the date the post was created. -->
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        <!-- loop through all categories assigned to the post. -->
        {% for category in post.categories.all %}
        <a href="{% url 'ps_blog_app:blog_category' category.name %}">{{ category.name }}</a>&nbsp; 
        {% endfor %}
    </small>
    <!-- slice is a django template filter that will cut off the post body at 400 chars. -->
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

ps_blog_project/templates/ps_blog_app/blog_detail.html
{%extends 'ps_blog_app/base.html'%}

{% block body_block %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="/ps_blog_app/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

ps_blog_project/templates/ps_blog_app/blog_index.html
{% extends 'ps_blog_app/base.html' %}
<!DOCTYPE html>
{% block body_block %}
<div class='container'>
  <div class='row'>
<div class='col-sm-12 col-md-12 col-lg-12 col-xs-12'>
    <h1 id='blog_index_header'>MGblogs</h1>
    
    <hr>
    {% for post in posts %}
    <!-- link to the blog_detail view and show the post title -->
    <h2><a href="{% url 'ps_blog_app:blog_detail' post.pk %}">{{ post.title }}</a></h2>
    <small>
        <!-- show the date the post was created. -->
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        <!-- loop through all categories assigned to the post. -->
        {% for category in post.categories.all %}
        <a href="{% url 'ps_blog_app:blog_category' category.name %}">{{ category.name }}</a>&nbsp; 
        {% endfor %}
    </small>
    <!-- slice is a django template filter that will cut off the post body at 400 chars. -->
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
</div>
</div>
{% endblock %}

ps_blog_project/templates/ps_blog_app/create_blog.html
{% extends 'ps_blog_app/base.html' %}


{%block body_block %}
<div class="jumbotron"><h1 style="color: #2995e2;">Create a post on our blog!</h1></div>

&nbsp;
<body>
<div class="container">
    <div class="container"><h3>1.) Choose a category </h3></div>
    &nbsp;
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="categories_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categories
    </button>
    <div class="dropdown-menu" aria-labelledby="categories_dropdown">
        {% for category in categories %}
        <a class="dropdown-item" href="#">{{ category.name }}</a>
        {% endfor %}
    </div>
</div>
&nbsp;
<hr>
<div class="container"><h3>2.) Fill out your blog post </h3></div>
<div class="container">
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ blog_form.as_p }}
        <input class='btn btn-primary' type='submit' value='post'> 
    </form>
</div>
</div>
</body>
{% endblock %}

ps_blog_project/templates/ps_blog_app/login.html
{% extends 'ps_blog_app/base.html'%}

{%block body_block %}
<div class='jumbotron'>
    <div class='col-md-8 offset-md-2'>
        <h1 id='register_header'>login page</h1>
        <hr>
    </div>
</div>
{% if logged_in_form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

    <form action="{% url 'login' %}" method='post'>
        {% csrf_token %}
        {% if not logged_in %}
        {{ login_form.as_p }}
        <input class='btn btn-primary' type='submit' value='login'>
        {% endif %}
    </form>

{% endblock %}

ps_blog_project/templates/ps_blog_app/register.html
{% extends 'ps_blog_app/base.html' %}
{% block body_block %}


<div class='jumbotron'>
    <div class='col-md-8 offset-md-2'>
        <h1 id='register_header'>registration page</h1>
        <hr>
    </div>
</div>
    {% if registered %}
    <div class='col-md-8 offset-md-2'>
      <h1>Thank you for registering </h1>
      <h3>You can start making some posts!</h3>
   </div>

    {% else %}
    <div class='col-md-8 offset-md-2'>
    <h3>Fill out the form and become a member of ps blogs!</h3>
    <form method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ user_form.as_p }}
        <input class='btn btn-primary' type='submit' value='register'>  
    </form>
    </div>

    {% endif %}
    

{% endblock %}

ps_blog_project/templates/ps_blog_app/upcoming.html
{% extends 'ps_blog_app/base.html'%}

{% block body_block %}
<div class='jumbotron'>
    <h1 id='upcoming_header'>New upcoming titles for Playstation 5</h1>
</div>
<div class="container">
<div class="row">
<div class='col-md-8 offset-md-2'>

    <img src="https://static.wikia.nocookie.net/horizonzerodawn/images/e/e5/Horizon_Forbidden_West.jpg/revision/latest?cb=20200613022428" width='700' height='500' style="border: 5px solid rgb(0, 0, 0);" alt="Horizion Forbbiden West">
    <h4>Title: Horizion Forbidden West</h4>
    <h4>Platform: PS5</h4>
    <h4>Developer: Guerilla Games</h4>
</div>
</div>

<div class="row">
<div class = "col-md-8 offset-md-2">
    <img src="https://d1lss44hh2trtw.cloudfront.net/assets/article/2021/01/14/god-of-war-ragnarok-release-date_feature.jpg" width='700' height='500' style="border: 5px solid rgb(0, 0, 0);" alt="Horizion Forbbiden West">
    <h4>Title: God of War Ragnarok</h4>
    <h4>Platform: PS5</h4>
    <h4>Developer: Santa Monica Studios</h4>
</div>
</div> 

<div class="row">
<div class = "col-md-8 offset-md-2">
    <img src="https://static.wikia.nocookie.net/ratchet/images/0/0e/Rift_Apart_logo.png/revision/latest?cb=20201002020119" width='700' height='500' style="border: 5px solid rgb(0, 0, 0);" alt="Horizion Forbbiden West">
    <h4>Title: Ratchet and Clank Rift Apart</h4>
    <h4>Platform: PS5</h4>
    <h4>Developer: Insomniac Games</h4>
</div>
</div> 

</div>

{% endblock %}